name: biometric_login
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0
  provider: ^6.1.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.5.2
  biometric_signature: ^6.2.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/



